version: '3.8'

services:
  cfst-server:
    image: ghcr.io/dirige/cf-test:latest
    container_name: cfst-server
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
