name: Build Docker Image

on:
  push:
    branches:
      - mimo
    paths:
      - 'cfst-server/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./cfst-server
          push: false
          platforms: linux/amd64,linux/arm64
          tags: cfst-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
